version: '3.8'
# To run this file, execute the following command:
# docker compose -f {compose file name} up
# This create and starts the containers

services:
  serviceregistry:
    build: .
    container_name: ServiceRegistry
    ports:
      - 8082:8761